[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "21"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/slidev/*"
to = "/slidev/index.html"
status = 200

[[redirects]]
from = "/slidev2/*"
to = "/slidev2/index.html"
status = 200
