[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "21"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/slidev1/*"
to = "/slidev1/index.html"
status = 200

[[redirects]]
from = "/slidev2/*"
to = "/slidev2/index.html"
status = 200

[[redirects]]
from = "/slidev3/*"
to = "/slidev3/index.html"
status = 200
